### ISSUE TITLE
1.7

### ISSUE THREAD

**Issue by 3rd-Eden** [adobe/Spry#1]
Hey,

I see that source code of Spry 1.6.1 is only released, are there plans to release the source code of Spry 1.7 as well?

**Comment by sarthaksinghal** [comment]
Can you share any references of Spry 1.7?

**Comment by 3rd-Eden** [comment]
http://labs.adobe.com/technologies/spry/preview/
http://labs.adobe.com/technologies/spry/ui/

**Comment by karneaud** [comment]
http://spry-it.appspot.com/... I mus however express my deepest disappointment with this move. Spry DataSet framework is by far a way better solution than using jquery in data display and manipulation. I would really HATE to see such a promising framework go to waste because of some super corporate decision and hopes someone else takes over this project and progress it into the potentially best data based manipulation framework it should be

**Comment by 3rd-Eden** [comment]
@karneaud spry-it is also my service that I build on top of the Google App engine, the source code for those files are available at https://github.com/3rd-Eden/Spry-Configurator/tree/master/js

**Comment by karneaud** [comment]
Nice work.....are you planning on developing further?

**Comment by 3rd-Eden** [comment]
@karneaud I was gonna release a new version of it when Spry 1.7 would launch, but that is not gonna happen anymore it seems.

**Comment by filmaj** [comment]
Hello, sorry, but this project is no longer maintained and will be going into an archived state. If you wish to revive it, consider forking it!
